version: 1

update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: master
    default_reviewers:
      - BoboTiG
    default_labels:
      - dependencies
