version: 1

update_configs:
  - package_manager: python
    directory: /tools/deps
    update_schedule: live
    target_branch: master
    default_assignees:
      - BoboTiG
    default_labels:
      - dependencies
