# src: https://docs.landscape.io/configuration.html

# Currently Python 2.7 only
python-targets:
  - 2

# Severity of the code quality checker
strictness: veryhigh
# Perhaps too much for now, but to activate later
doc-warnings: false
test-warnings: false

# Requirements
requirements:
  - requirements.txt
  - requirements-mac.txt
  - requirements-unix.txt
  - requirements-windows.txt
autodetect: true

# Skipped directories
ignore-paths:
  - docs
  - ftest
  - nuxeo-drive-client/tests
  - tools
