# Beta opt-in
# https://docs.travis-ci.com/user/build-config-validation#beta-opt-in
version: ~> 1.0

language: shell
dist: xenial
os: linux

env:
  global:
    - MAKEFLAGS="-j 2"
    - NXDRIVE_TEST_NUXEO_URL="https://nuxeo-drive-preview.platform.dev.nuxeo.com/nuxeo"
    # Set to "release" for a beta release
    - RELEASE_TYPE="alpha"
    # This is temporary, remove with NXDRIVE-2400
    - TESTING="1"

_before_script: &_before_script
  before_script:
    - |
      echo "${SSH_PRIV_KEY}" | base64 --decode > private.key
      chmod 0600 private.key
      eval "$(ssh-agent -s)"
      ssh-add private.key
      rm private.key
    - git config user.email "maintainers-python+travis@nuxeo.com"
    - git config user.name "Travis-CI bot"
    - git fetch --unshallow --tags
    - bash tools/bump-alpha-version.sh || exit 1

_build: &_build
  stage: Build
  <<: *_before_script
  script:
    - bash tools/$TRAVIS_OS_NAME/travis.sh
  after_failure:
    - bash tools/release.sh --cancel

jobs:
  fast_finish: true
  include:

  # This is temporary, enable back with NXDRIVE-2400
  # - <<: *_build
  #   name: GNU/Linux [.AppImage]
  #   services:
  #     - docker
  #   # addons:
  #   #   apt:
  #   #     packages:
  #   #     - appstream

  - <<: *_build
    name: macOS [.dmg]
    os: osx
    osx_image: xcode10.1  # macOS 10.13
    env:
      - KEYCHAIN_PATH="~/Library/Keychains/drive.keychain-db"
      - SIGNING_ID="NUXEO CORP"

  - <<: *_build
    name: Windows [.exe]
    os: windows
    env:
      - INNO_SETUP_VERSION="6.1.2"  # XXX_INNO_SETUP
      - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      - SIGNING_ID="Nuxeo"
      - SIGNTOOL_PATH="C:\Program Files (x86)\Windows Kits\10\bin\x86"

  - stage: Deploy
    <<: *_before_script
    script:
      - |
        if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
          # SSH key import
          echo "${TRAVIS_DEPLOY_KEY}" | base64 --decode > private.key
          chmod 0600 private.key
          ssh-add private.key
          rm private.key

          # Tel git to use the SSH access rather than HTTPS
          git remote set-url origin git@github.com:nuxeo/nuxeo-drive.git

          # Do the release
          bash tools/release.sh --publish "$RELEASE_TYPE" || exit 1
          bash tools/release.sh --create "$RELEASE_TYPE" || exit 1
        fi
    after_failure:
      - bash tools/release.sh --cancel
