#!/bin/bash -xe

MAJOR_VERSION=${MAJOR_VERSION:-$1}
MINOR_VERSION=${MINOR_VERSION:-$2}
RELEASE_VERSION=${RELEASE_VERSION:-$3}

[ -n "$MAJOR_VERSION" ]
[ -n "$MINOR_VERSION" ]
[ -n "$RELEASE_VERSION" ]

VERSION=$MAJOR_VERSION.$MINOR_VERSION.$RELEASE_VERSION
PROTOCOL=http
STAGING_SITE=community.nuxeo.com/static/drive-tests
PROD_SITE=community.nuxeo.com/static/drive
SSH_STRING=nuxeo@lethe.nuxeo.com
START_PATH=/var/www
APP_NAME=nuxeo-drive
OSX_UPDATE_APP_NAME="Nuxeo\ Drive"

echo Deploying Nuxeo Drive $VERSION from $PROTOCOL://$STAGING_SITE to $PROTOCOL://$PROD_SITE
ssh $SSH_STRING "cp $START_PATH/$STAGING_SITE/$VERSION.json $START_PATH/$STAGING_SITE/$APP_NAME-$VERSION* $START_PATH/$STAGING_SITE/$OSX_UPDATE_APP_NAME-$VERSION.* $START_PATH/$PROD_SITE"


