class Formatter:
    def __init__(self, *args, **kwargs) -> None: ...

class Logger:
    def info(self, *args, **kwargs) -> None: ...
    def trace(self, *args, **kwargs) -> None: ...
    def debug(self, *args, **kwargs) -> None: ...
    def error(self, *args, **kwargs) -> None: ...
    def warning(self, *args, **kwargs) -> None: ...
    def critical(self, *args, **kwargs) -> None: ...
    def exception(self, *args, **kwargs) -> None: ...

    def addHandler(*args, **kwargs) -> None: ...
    def getEffectiveLevel(self): ...
    def setLevel(self, *args, **kwargs) -> None: ...
    handlers: list

class StreamHandler: ...


def addLevelName(level: int, name: str): ...
def getLogger(name: str = None) -> Logger: ...
